### ISSUE TITLE
[FEAT] 데이터베이스 구현

### ISSUE THREAD

**Issue by oreocube** [oreocube/HRHN#10]
## Task
- [x] 엔티티 정의
- [x] 날짜 구간 조회
- [x] Room 데이터베이스 구현
- [x] 오늘의 챌린지 화면 연동 테스트

**Comment by chaneeii** [comment]
@oreocube  하잉!

추후에 업데이트 가능한 부분은 다음과 같음
- [ ] 업데이트 (각 날짜별)
- [ ] 삭제 

추가적으로 고려해야하는부분
- 가장 최근 아이템을 가져와야함 (어제가 아님) 

![스크린샷 2022-12-23 오후 9 24 06](https://user-images.githubusercontent.com/63157395/209335818-fc4f1061-05cb-4712-903d-bc459308b677.png)
