### ISSUE TITLE
챌린지 등록 - 지난 챌린지 평가

### ISSUE THREAD

**Issue by oreocube** [oreocube/HRHN#6]
## Screen Type
- 챌린지 등록

## Task
- [x] 지난 챌린지 평가 화면 레이아웃
- [x] 리사이클러뷰 구현
- [x] 선택된 아이템이 없는 경우 다음 버튼 비활성화
- [x] 화면 크기 대응
